# Generated by Django 4.1.3 on 2022-12-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcastapp", "0004_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banned", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(
                        default="default/default_avatar.jpg", upload_to="avatar_pic/"
                    ),
                ),
                (
                    "host",
                    models.ManyToManyField(
                        related_name="owner", to="podcastapp.podcast"
                    ),
                ),
                (
                    "subscriptions",
                    models.ManyToManyField(blank=True, to="podcastapp.podcast"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
