# Generated by Django 4.1.3 on 2022-12-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0005_alter_podcast_creation_date"),
        ("profileManagementApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="host",
            field=models.ManyToManyField(
                related_name="user_profiles", to="podcastapp.podcast"
            ),
        ),
    ]
