# Generated by Django 4.1.3 on 2022-12-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0005_alter_podcast_creation_date"),
        ("profileManagementApp", "0002_alter_userprofile_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="host",
            field=models.ManyToManyField(
                blank=True, related_name="user_profiles", to="podcastapp.podcast"
            ),
        ),
    ]
