# Generated by Django 4.1.3 on 2023-01-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profileManagementApp", "0003_alter_userprofile_host"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="host",),
        migrations.RemoveField(model_name="userprofile", name="subscriptions",),
    ]
