# Generated by Django 4.1.3 on 2023-02-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileManagementApp", "0004_remove_userprofile_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                to="profileManagementApp.userprofile",
            ),
        ),
    ]
