# Generated by Django 4.1.3 on 2022-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0002_alter_userprofile_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="host",
            field=models.ManyToManyField(related_name="owner", to="podcastapp.podcast"),
        ),
    ]
