# Generated by Django 4.1.3 on 2022-12-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0003_userprofile_host"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
