# Generated by Django 4.1.3 on 2023-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0005_alter_podcast_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
