# Generated by Django 4.1.3 on 2023-01-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profileManagementApp", "0004_remove_userprofile_host_and_more"),
        ("podcastapp", "0007_episode_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode", name="dislikes", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="episode",
            name="guest",
            field=models.ManyToManyField(to="profileManagementApp.userprofile"),
        ),
        migrations.AddField(
            model_name="episode", name="likes", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="episode",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="podcast",
            name="host",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_profiles",
                to="profileManagementApp.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subcriptions",
                to="profileManagementApp.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("content", models.CharField(max_length=1000)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcastapp.episode",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profileManagementApp.userprofile",
                    ),
                ),
            ],
        ),
    ]
