# Generated by Django 4.1.3 on 2023-01-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileManagementApp", "0004_remove_userprofile_host_and_more"),
        ("podcastapp", "0008_episode_dislikes_episode_guest_episode_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="guest",
            field=models.ManyToManyField(
                blank=True, to="profileManagementApp.userprofile"
            ),
        ),
    ]
