# Generated by Django 4.1.3 on 2023-01-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profileManagementApp", "0004_remove_userprofile_host_and_more"),
        ("podcastapp", "0010_invitation"),
    ]

    operations = [
        migrations.RemoveField(model_name="invitation", name="blia",),
        migrations.AddField(
            model_name="invitation",
            name="from_user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="profileManagementApp.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="to_user_user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="profileManagementApp.userprofile",
            ),
        ),
    ]
