# Generated by Django 4.1.3 on 2023-01-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "podcastapp",
            "0011_remove_invitation_blia_invitation_from_user_profile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="podcastapp.episode",
            ),
        ),
    ]
