# Generated by Django 4.1.3 on 2023-01-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0012_alter_invitation_episode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="to_user_user_profile",
            new_name="to_user_profile",
        ),
    ]
