# Generated by Django 4.1.3 on 2023-01-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileManagementApp", "0004_remove_userprofile_host_and_more"),
        ("podcastapp", "0014_alter_invitation_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="favourite_episodes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_episode",
                to="profileManagementApp.userprofile",
            ),
        ),
    ]
