# Generated by Django 4.1.3 on 2023-02-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0015_episode_favourite_episodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment", name="reports", field=models.IntegerField(default=0),
        ),
    ]
