# Generated by Django 4.1.3 on 2023-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcastapp", "0017_alter_episode_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="audio",
            field=models.FileField(null=True, upload_to="audio_files/"),
        ),
    ]
